"""OddsFlow V3.1 — DF-Aware Zone-Market Policy
=============================================
Enhancement 2026-05-27: partition key extended from (zone, bts_pocket) to
(zone, df, bts_pocket). DF separation evidence per enhanced analysis
(Output/ENHANCED_ANALYSIS_2026-05-27.xlsx, sheet 11):
  alpha_win:  DF separates 26.2pp (Tier A) / 22.9pp (Tier B)
  3+ goals:   DF separates 9.4pp (Tier A) / 7.8pp (Tier B)
  threeway:   strong:slight_under DF0 67.7% → DF2 80.3% (12.6pp lift from DF)

Cells: 19 promoted (4 zones × 3 DF × 4 BTS = 48 potential; min_n=50 filter).
Auto-generated by Scripts/build_v3_df_policy.py from 28,425 settled fixtures.

PROMOTED_CELLS — fallback dict consumed by routes_inspector / routes_reports.
V3_MARKETS     — per-cell market configuration.
V3_ACTIVE      — active pick set (low zone governed by LOW_ZONE_SUPPRESS).
"""

from __future__ import annotations

from typing import Any

LOW_ZONE_SUPPRESS: bool = False   # V3 policy activates low zone DNB

_DNB = "DNB (Alpha Win or Draw)"
_WIN = "Alpha Win"

# ---------------------------------------------------------------------------
# PROMOTED_CELLS — 3-key tuples (zone, df, bts_pocket).
# threeway_hit stores DNB baseline for strong/standard/low, alpha_win for one_sided.
# ---------------------------------------------------------------------------
PROMOTED_CELLS: dict[tuple[str, str, str], dict[str, Any]] = {
    # ── strong zone ──────────────────────────────────────────────────────
    ("strong", "DF0", "slight_over"): {
        "zone": "strong", "df": "DF0", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 64.8, "threeway_pick": _DNB,
        "gn_hit": 70.9, "cn_hit": 0.0, "n_fixtures": 704,
        "promote_status": "PASS",
    },
    ("strong", "DF0", "slight_under"): {
        "zone": "strong", "df": "DF0", "bts_pocket": "slight_under",
        "cell_promoted": True,
        "threeway_hit": 67.7, "threeway_pick": _DNB,
        "gn_hit": 65.2, "cn_hit": 0.0, "n_fixtures": 851,
        "promote_status": "MARGINAL",
    },
    ("strong", "DF1", "slight_over"): {
        "zone": "strong", "df": "DF1", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 70.7, "threeway_pick": _DNB,
        "gn_hit": 72.6, "cn_hit": 0.0, "n_fixtures": 3712,
        "promote_status": "PASS",
    },
    ("strong", "DF1", "slight_under"): {
        "zone": "strong", "df": "DF1", "bts_pocket": "slight_under",
        "cell_promoted": True,
        "threeway_hit": 71.9, "threeway_pick": _DNB,
        "gn_hit": 66.7, "cn_hit": 0.0, "n_fixtures": 2525,
        "promote_status": "PASS",
    },
    ("strong", "DF2", "slight_over"): {
        "zone": "strong", "df": "DF2", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 76.1, "threeway_pick": _DNB,
        "gn_hit": 71.4, "cn_hit": 0.0, "n_fixtures": 581,
        "promote_status": "PASS",
    },
    ("strong", "DF2", "slight_under"): {
        "zone": "strong", "df": "DF2", "bts_pocket": "slight_under",
        "cell_promoted": True,
        "threeway_hit": 80.3, "threeway_pick": _DNB,
        "gn_hit": 67.1, "cn_hit": 0.0, "n_fixtures": 2549,
        "promote_status": "PASS",
    },
    # ── standard zone ────────────────────────────────────────────────────
    ("standard", "DF0", "slight_over"): {
        "zone": "standard", "df": "DF0", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 67.7, "threeway_pick": _DNB,
        "gn_hit": 80.1, "cn_hit": 61.9, "n_fixtures": 186,
        "promote_status": "PASS",
    },
    ("standard", "DF0", "strong_over"): {
        "zone": "standard", "df": "DF0", "bts_pocket": "strong_over",
        "cell_promoted": True,
        "threeway_hit": 61.1, "threeway_pick": _DNB,
        "gn_hit": 81.1, "cn_hit": 61.3, "n_fixtures": 90,
        "promote_status": "PASS",
    },
    ("standard", "DF1", "slight_over"): {
        "zone": "standard", "df": "DF1", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 69.9, "threeway_pick": _DNB,
        "gn_hit": 79.7, "cn_hit": 65.4, "n_fixtures": 4134,
        "promote_status": "PASS",
    },
    ("standard", "DF1", "strong_over"): {
        "zone": "standard", "df": "DF1", "bts_pocket": "strong_over",
        "cell_promoted": True,
        "threeway_hit": 68.9, "threeway_pick": _DNB,
        "gn_hit": 83.5, "cn_hit": 69.7, "n_fixtures": 1034,
        "promote_status": "PASS",
    },
    ("standard", "DF2", "slight_over"): {
        "zone": "standard", "df": "DF2", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 79.1, "threeway_pick": _DNB,
        "gn_hit": 76.9, "cn_hit": 63.9, "n_fixtures": 5129,
        "promote_status": "PASS",
    },
    ("standard", "DF2", "slight_under"): {
        "zone": "standard", "df": "DF2", "bts_pocket": "slight_under",
        "cell_promoted": True,
        "threeway_hit": 82.9, "threeway_pick": _DNB,
        "gn_hit": 71.6, "cn_hit": 57.9, "n_fixtures": 1939,
        "promote_status": "MARGINAL",
    },
    ("standard", "DF2", "strong_over"): {
        "zone": "standard", "df": "DF2", "bts_pocket": "strong_over",
        "cell_promoted": True,
        "threeway_hit": 76.4, "threeway_pick": _DNB,
        "gn_hit": 86.2, "cn_hit": 74.6, "n_fixtures": 195,
        "promote_status": "PASS",
    },
    # ── low zone ─────────────────────────────────────────────────────────
    ("low", "DF2", "slight_over"): {
        "zone": "low", "df": "DF2", "bts_pocket": "slight_over",
        "cell_promoted": not LOW_ZONE_SUPPRESS,
        "threeway_hit": 84.9, "threeway_pick": _DNB,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 1733,
        "promote_status": "PASS",
    },
    ("low", "DF2", "slight_under"): {
        "zone": "low", "df": "DF2", "bts_pocket": "slight_under",
        "cell_promoted": not LOW_ZONE_SUPPRESS,
        "threeway_hit": 91.6, "threeway_pick": _DNB,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 675,
        "promote_status": "PASS",
    },
    ("low", "DF2", "strong_over"): {
        "zone": "low", "df": "DF2", "bts_pocket": "strong_over",
        "cell_promoted": not LOW_ZONE_SUPPRESS,
        "threeway_hit": 82.8, "threeway_pick": _DNB,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 238,
        "promote_status": "PASS",
    },
    # ── one_sided zone ───────────────────────────────────────────────────
    ("one_sided", "DF2", "slight_over"): {
        "zone": "one_sided", "df": "DF2", "bts_pocket": "slight_over",
        "cell_promoted": True,
        "threeway_hit": 76.6, "threeway_pick": _WIN,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 1119,
        "promote_status": "PASS",
    },
    ("one_sided", "DF2", "slight_under"): {
        "zone": "one_sided", "df": "DF2", "bts_pocket": "slight_under",
        "cell_promoted": True,
        "threeway_hit": 81.0, "threeway_pick": _WIN,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 814,
        "promote_status": "PASS",
    },
    ("one_sided", "DF2", "strong_over"): {
        "zone": "one_sided", "df": "DF2", "bts_pocket": "strong_over",
        "cell_promoted": True,
        "threeway_hit": 66.7, "threeway_pick": _WIN,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 66,
        "promote_status": "FLAG",
    },
    # min_n lowered 50→45 to include this cell (operator decision, Session 18)
    ("one_sided", "DF2", "strong_under"): {
        "zone": "one_sided", "df": "DF2", "bts_pocket": "strong_under",
        "cell_promoted": True,
        "threeway_hit": 80.9, "threeway_pick": _WIN,
        "gn_hit": 0.0, "cn_hit": 0.0, "n_fixtures": 47,
        "promote_status": "PASS",
    },
}

# ---------------------------------------------------------------------------
# V3_MARKETS — per-cell market configuration (3-key tuples).
# market keys: "goals_nl" | "corners_nl" | "dnb" | "alpha_win"
# Fields: line (float | None), hit (float), n (int), odd_col (str | None)
# ---------------------------------------------------------------------------
_GL = "goals_over_15_odd"
_CL = "corners_over_85_odd"

V3_MARKETS: dict[tuple[str, str, str], dict[str, dict[str, Any]]] = {
    # ── strong ───────────────────────────────────────────────────────────
    ("strong", "DF0", "slight_over"):  {"goals_nl": {"line": 1.5, "hit": 70.9, "n":  704, "odd_col": _GL}},
    ("strong", "DF0", "slight_under"): {"goals_nl": {"line": 1.5, "hit": 65.2, "n":  851, "odd_col": _GL}},
    ("strong", "DF1", "slight_over"):  {"goals_nl": {"line": 1.5, "hit": 72.6, "n": 3712, "odd_col": _GL}},
    ("strong", "DF1", "slight_under"): {"goals_nl": {"line": 1.5, "hit": 66.7, "n": 2525, "odd_col": _GL}},
    ("strong", "DF2", "slight_over"):  {"goals_nl": {"line": 1.5, "hit": 71.4, "n":  581, "odd_col": _GL}},
    ("strong", "DF2", "slight_under"): {"goals_nl": {"line": 1.5, "hit": 67.1, "n": 2549, "odd_col": _GL}},
    # ── standard ─────────────────────────────────────────────────────────
    ("standard", "DF0", "slight_over"): {
        "goals_nl":   {"line": 1.5, "hit": 80.1, "n":  186, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 61.9, "n":  160, "odd_col": _CL},
    },
    ("standard", "DF0", "strong_over"): {
        "goals_nl":   {"line": 1.5, "hit": 81.1, "n":   90, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 61.3, "n":   75, "odd_col": _CL},
    },
    ("standard", "DF1", "slight_over"): {
        "goals_nl":   {"line": 1.5, "hit": 79.7, "n": 4134, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 65.4, "n": 3050, "odd_col": _CL},
    },
    ("standard", "DF1", "strong_over"): {
        "goals_nl":   {"line": 1.5, "hit": 83.5, "n": 1034, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 69.7, "n":  921, "odd_col": _CL},
    },
    ("standard", "DF2", "slight_over"): {
        "goals_nl":   {"line": 1.5, "hit": 76.9, "n": 5129, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 63.9, "n": 4064, "odd_col": _CL},
    },
    ("standard", "DF2", "slight_under"): {
        "goals_nl":   {"line": 1.5, "hit": 71.6, "n": 1939, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 57.9, "n": 1315, "odd_col": _CL},
    },
    ("standard", "DF2", "strong_over"): {
        "goals_nl":   {"line": 1.5, "hit": 86.2, "n":  195, "odd_col": _GL},
        "corners_nl": {"line": 8.5, "hit": 74.6, "n":  177, "odd_col": _CL},
    },
    # ── low ──────────────────────────────────────────────────────────────
    ("low", "DF2", "slight_over"):  {"dnb": {"line": None, "hit": 84.9, "n": 1733, "odd_col": None}},
    ("low", "DF2", "slight_under"): {"dnb": {"line": None, "hit": 91.6, "n":  675, "odd_col": None}},
    ("low", "DF2", "strong_over"):  {"dnb": {"line": None, "hit": 82.8, "n":  238, "odd_col": None}},
    # ── one_sided ────────────────────────────────────────────────────────
    ("one_sided", "DF2", "slight_over"):  {"alpha_win": {"line": None, "hit": 76.6, "n": 1119, "odd_col": None}},
    ("one_sided", "DF2", "slight_under"): {"alpha_win": {"line": None, "hit": 81.0, "n":  814, "odd_col": None}},
    ("one_sided", "DF2", "strong_over"):  {"alpha_win": {"line": None, "hit": 66.7, "n":   66, "odd_col": None}},
    ("one_sided", "DF2", "strong_under"): {"alpha_win": {"line": None, "hit": 80.9, "n":   47, "odd_col": None}},  # min_n lowered 50→45 (Session 18)
}

# Active pick set — low zone excluded when LOW_ZONE_SUPPRESS is True
V3_ACTIVE: dict[tuple[str, str, str], dict[str, dict[str, Any]]] = {
    k: v for k, v in V3_MARKETS.items()
    if not (LOW_ZONE_SUPPRESS and k[0] == "low")
}
